services:
  nginx_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - product_service

  user_service:
    build:
      context: .
      dockerfile: Dockerfile.user

  product_service:
    build:
      context: .
      dockerfile: Dockerfile.product
